"""Frozen result-independent contracts for terminal SPLITCLOCK Stage-0A R2."""

from __future__ import annotations

BASE_SHA = "38cddccd9d02a9c0da4052375e4d1168e2cc58cb"
BRANCH = "research/splitclock-stage0a-r2-terminal-contract-repair"
R1_ARTIFACT = "artifacts/splitclock_stage0a_r1_contract_model_repair"
R2_ARTIFACT = "artifacts/splitclock_stage0a_r2_terminal_contract_repair"
R1_DESIGN_SHA = "d472376ba2e59d766c93296b4755df4c89ccbe9b"
R1_IMPLEMENTATION_SHA = "3b2d943b15eed67df55051c123682ac92453a699"
R1_FINAL_SHA = BASE_SHA
REPAIR_SCOPE_MESSAGE = "SPLITCLOCK_STAGE0A_R2_REPAIR_SCOPE_FREEZE"
IMPLEMENTATION_MESSAGE = "SPLITCLOCK_STAGE0A_R2_IMPLEMENTATION_FREEZE"

WINDOW_EPOCHS = 10
FIT_EPOCHS = 7
HOLDOUT_EPOCHS = 3
STUDENT_T_DF = 4.0
MIN_CLUSTER_MASS = 2.0
PERSISTENCE = 3
HORIZON_EPOCHS = 20
SEED = 20250824

ALLOWED_VERDICTS = (
    "STOP_SPLITCLOCK_R2_GEOMETRY_OR_PANEL",
    "INCONCLUSIVE_SPLITCLOCK_R2_IMPLEMENTATION_CONTRACT",
    "INCONCLUSIVE_SPLITCLOCK_R2_EXECUTION_OR_PROVENANCE",
    "NO_GO_SPLITCLOCK_R2_CLEAN_FALSE_ALARMS",
    "NO_GO_SPLITCLOCK_R2_NEGATIVE_CONTROLS",
    "NO_GO_SPLITCLOCK_R2_SYNTHETIC_IDENTIFIABILITY",
    "READY_FOR_SPLITCLOCK_ATTACK_FREEZE",
)

FORBIDDEN_MODEL_INPUTS = (
    "prn_number",
    "filename",
    "scenario_label",
    "cn0_db_hz",
    "lock",
    "prn_count",
)
